### ISSUE TITLE
"invalid start byte" error accessing variant.alleles in pyodide/jupyterlite

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit#2737]
When I try to run the following in a [jupyterlite](https://jupyter.org/try-jupyter/lab/index.html) notebook (using chrome 112.0.5615.49 under OS X):

```python
import msprime

print("msprime v:", msprime.__version__, ", tskit v:", tskit.__version__)

ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
next(ts.variants()).alleles
```

I get

```
msprime v: 1.2.0 , tskit v: 0.5.4
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[4], line 7
      4 print("msprime v:", msprime.__version__, ", tskit v:", tskit.__version__)
      6 ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
----> 7 next(ts.variants()).alleles

File /lib/python3.11/site-packages/tskit/genotypes.py:151, in Variant.alleles(self)
    143 @property
    144 def alleles(self) -> tuple[str | None, ...]:
    145     """
    146     A tuple of the allelic values which samples can possess at the current
    147     site. Unless an encoding of alleles is specified when creating this
    148     variant instance, the first element of this tuple is always the site's
    149     ancestral state.
    150     """
--> 151     return self._ll_variant.alleles

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4: invalid start byte
```

**Comment by hyanwong** [comment]
As you might expect, it's the same in pyodide (https://pyodide.org/en/stable/console.html):

```python
Welcome to the Pyodide terminal emulator 🐍
Python 3.11.2 (main, May  3 2023 04:00:05) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
>>> import tskit
>>> print("msprime v:", msprime.__version__, ", tskit v:", tskit.__version__)
ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
next(ts.variants()).alleles
msprime v: 1.2.0 , tskit v: 0.5.4
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/tskit/genotypes.py", line 151, in alleles
    return self._ll_variant.alleles
           ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4: invalid start byte
>>> 
```

**Comment by jeromekelleher** [comment]
Hmm, sounds like we need to be more explicit about the encoding we're using somewhere. Perhaps the default for CPython and Pyiodide is different? I would have thought both were UTF-8, so I'm confused.

Maybe [here](https://github.com/tskit-dev/tskit/blob/be7d84f7a014c679c9e303aa7a8145b440f73bd3/python/_tskitmodule.c#L581)?

I guess the other option is that the alleles are somehow including uninitialised bytes under pyiodide, but I don't see how that would happen either. Maybe because it's a 32 bit platform?

**Comment by benjeffery** [comment]
A quick fix might be to use `y#` and then do the utf-8 decode on the python side.

**Comment by benjeffery** [comment]
We should run our test suite on wasm if we're seriously supporting it.

**Comment by hyanwong** [comment]
> A quick fix might be to use y# and then do the utf-8 decode on the python side.

Presumably that would allow us to check if it was an uninitialised bytes problem.

**Comment by benjeffery** [comment]
I had a quick look - some of the deps aren't there (`pysam` and `xmlunittest`) we could disable the tests that need those.

Pytest doesn't immediately work - I didn't dig too much as it wasn't immediately obvious what was causing that.
I extracted `tests_highlevel.py` out into a separate directory and got that to run:

```
======================================== short test summary info =========================================
FAILED test_highlevel.py::TestTreeSequence::test_dump_load_errors - Failed: DID NOT RAISE <class 'OSError'>
FAILED test_highlevel.py::TestSimplify::test_simplify_bugs - assert 1 > 1
FAILED test_highlevel.py::TestSiteAlleles::test_k_mutations[0] - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4: invalid start byte
FAILED test_highlevel.py::TestSiteAlleles::test_k_mutations[1] - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4: invalid start byte
FAILED test_highlevel.py::TestSiteAlleles::test_k_mutations[2] - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte
FAILED test_highlevel.py::TestSiteAlleles::test_k_mutations[3] - UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 16-17: invalid continuation byte
FAILED test_highlevel.py::TestSiteAlleles::test_k_mutations[4] - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 24: invalid start byte
FAILED test_highlevel.py::TestTskitConversionOutput::test_macs - IndexError: string index out of range
FAILED test_highlevel.py::TestTskitConversionOutput::test_macs_error - IndexError: string index out of range
=================== 9 failed, 4215 passed, 1 skipped, 137 warnings in 60.79s (0:01:00) ===================

**Comment by jeromekelleher** [comment]
Hmm, no pytest is a deal-breaker, so let's not bother trying to get that working.

Maybe we should sort out the unicode problem locally (if you can use your setup) and file running the suite as a nice to have for later?

**Comment by benjeffery** [comment]
I've dug a bit deeper here and it's very odd. The Py_BuildValue call with `y#` is returning strings that are hundreds of characters longer than they should be. The first few characters are correct, so it's just grabbing more bytes than it is asked to. This explains the unicode error as it is trying to decide random memory.

**Comment by hyanwong** [comment]
Ah, nice digging. This is indeed very odd. Maybe a bug in string termination? Sound like it might not be a bug on our end, though.

**Comment by jeromekelleher** [comment]
Weird! Is the length we're providing correct? If so it's a bug in the implementation of s# and y#.

Should be able to put a printf in there to check?

**Comment by benjeffery** [comment]
Yeah, the length was correct.

@hyanwong I can't replicate this using the pyodide version at https://pyodide.org/en/stable/console.html
Which is `3.11.2 (main, May  3 2023, 04:00:05)` (Pyodide 0.23.2) a more recent version than `3.11.2 (main, Mar 30 2023, 21:37:59)`  (Pyodide 0.23.0) on the notebook demo site. 

I can't identify the commit that fixed this, but it look like it was fixed upstream.

**Comment by hyanwong** [comment]
Weird: I'm still getting this on pyodide 0.23.2 (Chrome 112.0.5615.137 / OS X). But it it an intermittent fault - it works here on the 3rd time (maybe because of what's in memory, though?)

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.11.2 (main, May  3 2023 04:00:05) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
>>> import pyodide
>>> pyodide.__version__
'0.23.2'
>>> ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
next(ts.variants()).alleles
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/tskit/genotypes.py", line 151, in alleles
    return self._ll_variant.alleles
           ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4: invalid start byte
>>> ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
next(ts.variants()).alleles
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/tskit/genotypes.py", line 151, in alleles
    return self._ll_variant.alleles
           ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4: invalid start byte
>>> ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=1, random_seed=1)
next(ts.variants()).alleles
('G', 'C', 'A', 'T')
>>> 
 ```

Could it be OS-specific perhaps?

If it's not our fault, not much we can do though, so no point re-opening this. I'm not sure how to report it to any upstream project, though?

**Comment by hyanwong** [comment]
And following up, I can repeatedly replicate the fact that this on the first two times running the .simulate command, and then succeeds on the 3rd time.

Out of interest @benjeffery, what do you get when you try something like:

```python
>>> for s in range(1, 1000):
...  ts = msprime.sim_mutations(msprime.sim_ancestry(10, sequence_length=10, random_seed=1), rate=0.1, random_seed=s)
...  print(next(ts.variants()).alleles)
```

? (no need to dig this deeper though, just wondering)

**Comment by hyanwong** [comment]
Also FWIW still happening in the "latest" pyodide. I will try to report a MWE to the pyodide repo.

**Comment by hyanwong** [comment]
This example of calling `Py_BuildValue` from javascript seems pretty useful for testing: https://github.com/pyodide/pyodide/issues/3846#issuecomment-1540610441

Here's an html page for quick testing, using that code:

```html
<!DOCTYPE html>
<html>
  <head>
      <script type="text/javascript">
          // set the pyodide files URL (packages.json, pyodide.asm.data etc)
          window.languagePluginUrl = 'https://cdn.jsdelivr.net/pyodide/v0.16.1/full/';
      </script>
      <script src="https://cdn.jsdelivr.net/pyodide/v0.16.1/full/pyodide.js"></script>
  </head>
  <body>
    Pyodide <code>Py_BuildValue</code> output:
    <textarea id='output' style='width: 100%;' rows='6' disabled></textarea>

    <script type="text/javascript">
        const output = document.getElementById("output");
        languagePluginLoader.then(function () {
            l_ptr = pyodide.runPython(`l = []; id(l)`)
            fmt_ptr = pyodide._module.stringToNewUTF8("s#");
            str_ptr = pyodide._module.stringToNewUTF8("hello there!");
            varargs_ptr = pyodide._module.stackAlloc(8);
            pyodide._module.HEAP32[varargs_ptr/4] = str_ptr;
            pyodide._module.HEAP32[varargs_ptr/4 + 1] = 10;
            pystr_ptr = pyodide._module.__Py_BuildValue_SizeT(fmt_ptr, varargs_ptr);
            if(pystr_ptr === 0){
                pyodide._module._pythonexc2js();
            }
            pyodide._module._PyList_Append(l_ptr, pystr_ptr);
            pyodide.runPython("print(l)")
            output.value = pyodide.globals.l;
        });
    </script>
  </body>
</html>
```

**Comment by jeromekelleher** [comment]
Turns out this is a problem in which we don't cast the length of the string to Py_ssize_t, which is an easy fix.

**Comment by hoodmane** [comment]
If you folks want advice about how to test against Pyodide, I can perhaps make you a PR. Also, have you considered using cibuildwheel?

**Comment by benjeffery** [comment]
Thanks @hoodmane! I did look into adding pyodide tests to the repo here, but got stuck getting pytest to work. If it isn't too much work for you we'd welcome a PR.

I can't remember why I didn't use `cibuildwheel` when I set up the wheel automation a couple of years back. I think we needed some custom stuff for other projects under tskit-dev and it was best to keep them all running something similar. As our current process is working I'm hesitant to dive in and change it, although next time something breaks I'll certainly consider switching.
